# 混合端口 HTTP 和 SOCKS5 用一个端口
mixed-port: 7890

# HTTP 代理端口
# port: 7890

# SOCKS5 代理端口
# socks-port: 7891

# Linux 和 macOS 的 redir 代理端口（如需使用此功能，请取消注释）
# redir-port: 7892

# 允许局域网的连接（可用来共享代理）
allow-lan: true

# 仅在将 allow-lan 设置为 true 时适用
# #"*": 绑定所有 IP 地址
# #192.168.122.11: 绑定单个 IPv4 地址
# #"[aaaa::a8aa:ff:fe09:57d8]": 绑定单个 IPv6 地址
bind-address: "*"
ipv6: true

# 规则模式：rule（规则） / global（全局代理）/ direct（全局直连）/ script（脚本）
# mode: rule

# 设置日志输出级别（默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / error / warning / info / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: silent

# Clash 的 RESTful API
external-controller: '127.0.0.1:9090'

# 实验性功能
experimental:
  ignore-resolve-fail: true # 忽略 DNS 解析失败，默认值为 true
  # interface-name: en0 # outbound interface name

# 本地 SOCKS5 / HTTP(S) 服务认证
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# 实验性功能 hosts, 支持通配符 (例如 *.clash.dev 甚至 *.foo.*.example.com)
# 静态的域名 比 通配域名 具有更高的优先级 (foo.example.com 优先于 *.example.com)
# 注意: hosts 在 fake-ip 模式下不生效

dns:
  enable: true
  enhanced-mode: fake-ip
  prefer-h3: true
  nameserver:
    - https://223.5.5.5/dns-query#h3=true
  fallback:
    - tls://1.1.1.1:853
    - quic://94.140.14.140:784
  ipv6: true
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"
      - "+.msftconnecttest.com"
      - "+.msftncsi.com"
  fake-ip-filter:
    # LAN
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    # NTP 服务
    - "time.*.com"
    - "time.*.gov"
    - "time.*.edu.cn"
    - "ntp.ntsc.ac.cn"
    - "time.*.apple.com"
    - "time1.*.com"
    - "time2.*.com"
    - "time3.*.com"
    - "time4.*.com"
    - "time5.*.com"
    - "time6.*.com"
    - "time7.*.com"
    - "ntp.*.com"
    - "ntp1.*.com"
    - "ntp2.*.com"
    - "ntp3.*.com"
    - "ntp4.*.com"
    - "ntp5.*.com"
    - "ntp6.*.com"
    - "ntp7.*.com"
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - "+.pool.ntp.org"
    - "ntp.*.cn"
    - "clock.neu.edu.cn"
    - "time1.cloud.tencent.com"
    - "time-ios.apple.com"
    # 网易云音乐
    - "+.music.163.com"
    - "+.126.net"
    # 百度音乐
    - "musicapi.taihe.com"
    - "music.taihe.com"
    # 酷狗音乐
    - "songsearch.kugou.com"
    - "trackercdn.kugou.com"
    # 酷我音乐
    - "+.kuwo.cn"
    # JOOX 音乐
    - "api-jooxtt.sanook.com"
    - "api.joox.com"
    - "joox.com"
    # QQ 音乐
    - "+.y.qq.com"
    - "streamoc.music.tc.qq.com"
    - "mobileoc.music.tc.qq.com"
    - "isure.stream.qqmusic.qq.com"
    - "dl.stream.qqmusic.qq.com"
    - "aqqmusic.tc.qq.com"
    - "amobile.music.tc.qq.com"
    # 虾米音乐
    - "+.xiami.com"
    # 咪咕音乐
    - "+.music.migu.cn"
    # Windows
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - WORKGROUP
    # QQ 快捷登录
    - "+.localhost.ptlogin2.qq.com"
    - "+.localhost.sec.qq.com"
    # Game
    # Nintendo Switch
    - "+.srv.nintendo.net"
    # Sony PlayStation
    - "+.stun.playstation.net"
    # Microsoft Xbox
    - "+.xbox.*.microsoft.com"
    - "+.xnotify.xboxlive.com"
    - "+.ipv6.microsoft.com"
    # World of Tanks CN
    - "+.battlenet.com.cn"
    - "+.wotgame.cn"
    - "+.wggames.cn"
    - "+.wowsgame.cn"
    - "+.wargaming.net"
    # Golang
    - "proxy.golang.org"
    # STUN
    - "+.stun.*"
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.pvp.net"
    # Linksys Router
    - "+.heartbeat.belkin.com"
    - "+.linksys.com"
    - "+.linksyssmartwifi.com"
    # ASUS Router
    - "+.router.asus.com"
    # Apple Software Update Service
    - "+.mesu.apple.com"
    - "+.swscan.apple.com"
    - "+.swquery.apple.com"
    - "+.swdownload.apple.com"
    - "+.swcdn.apple.com"
    - "+.swdist.apple.com"
    # Google
    - "+.lens.l.google.com"
    - "+.stun.l.google.com"
    # Firebase Cloud Messaging
    - "fcm.googleapis.com"
    - "mtalk.google.com"
    - "alt*-mtalk.google.com"
    # Huawei Push Service
    - "+.push.hicloud.com"
    - "+.push.dbankcloud.com"
    # Xiaomi Push Service
    - "api.xmpush.xiaomi.com"
    # APNs
    - "+.push.apple.com"
    # OPPO Push Service
    - "+.push.oppomobile.com"
    # VIVO Push Service
    - "api-push.vivo.com.cn"
    # Netflix
    - "+.nflxvideo.net"
    # FinalFantasy XIV
    - "+.square-enix.com"
    - "+.finalfantasyxiv.com"
    - "+.ffxiv.com"
    - "+.ff14.sdo.com"
    - "ff.dorado.sdo.com"
    # Bilibili CN
    - "+.mcdn.bilivideo.cn"
    # Disney Plus
    - "+.media.dssott.com"
